### ISSUE TITLE
problème remontées information de la borne

### ISSUE THREAD

**Issue by 889laurent** [ioxFR/jeedom-wallbox#2]
bonjour , j'ai essayé le plugin avec 1 bone cooper et pulsar et seul le statut de charge fonctionne (ready et charging). Pouvez vous regarder si le pb viens ce chez moi ?

merci d'avance.

cordialement

**Comment by ioxFR** [comment]
Bonjour à vous,

Je ne comprend pas d'un côté vous me dites que vous avez le statut charging et de l'autre comme quoi le statut ne remonte pas.
Auriez vous la possibilité de fournir des screenshot du resultat du plugin que vous avez?

Merci
